services:
  - type: web
    name: klangio-ai-server
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: export PATH=$PATH:$(pwd)/bin && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
